# Facebook Metrics Data

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
facebook= pd.read_csv("C:\\Users\\CLL\\Documents\\Github\\Ce888 Assignment\\Facebook Metrics\\dataset_Facebook.csv",sep=';')

FileNotFoundError: [Errno 2] File b'C:\\Users\\CLL\\Documents\\Github\\Ce888 Assignment\\Facebook Metrics\\dataset_Facebook.csv' does not exist: b'C:\\Users\\CLL\\Documents\\Github\\Ce888 Assignment\\Facebook Metrics\\dataset_Facebook.csv'

# 1. Explore the Data

In [79]:
print(facebook.columns)
len(facebook.columns)

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

19

In [80]:
len(facebook)
facebook.describe() # Description of data

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [81]:
print(facebook[:10])
print(set(facebook['Category']))
print(set(facebook['Type']))

   Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441   Photo         2          12             4          3
1            139441  Status         2          12             3         10
2            139441   Photo         3          12             3          3
3            139441   Photo         2          12             2         10
4            139441   Photo         2          12             2          3
5            139441  Status         2          12             1          9
6            139441   Photo         3          12             1          3
7            139441   Photo         3          12             7          9
8            139441  Status         2          12             7          3
9            139441   Photo         3          12             6         10

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091
1   0.0                      10460                            19057
2   0.0                       2413                             4373
3   1.0                      50128                            87991
4   0.0                       7244                            13594
5   0.0                      10472                            20849
6   1.0                      11692                            19479
7   1.0                      13720                            24137
8   0.0                      11844                            22538
9   0.0                       4694                             8668

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109
1                    1457                     1361
2                     177                      113
3                    2211                      790
4                     671                      410
5                    1191                     1073
6                     481                      265
7                     537                      232
8                    1530                     1407
9                     280                      183

   Lifetime Post Consumptions  \
0                         159
1                        1674
2                         154
3                        1119
4                         580
5                        1389
6                         364
7                         305
8                        1692
9                         250

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078
1                                              11710
2                                               2812
3                                              61027
4                                               6228
5                                              16034
6                                              15432
7                                              19728
8                                              15220
9                                               4309

   Lifetime Post reach by people who like your Page  \
0                                              1640
1                                              6112
2                                              1503
3                                             32048
4                                              3200
5                                              7852
6                                              9328
7                                             11056
8                                              7912
9                                              2324

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119
1                                               1108
2                                                132
3                                               1386
4                                                396
5                                               1016
6                                                379
7                                                422
8                                               1250
9                                                199

   comment    like  share  Total Interactions
0        4    79.0   17.0                 100
1        5   130.0   29.0                 164
2        0    66.0   14.0                  80
3       58  1572.0  147.0                1777
4       19   325.0   49.0                 393
5        1   152.0   33.0                 186
6        3   249.0   27.0                 279
7        0   325.0   14.0                 339
8        0   161.0   31.0                 192
9        3   113.0   26.0                 142
{1, 2, 3}
{'Photo', 'Status', 'Link', 'Video'}

In [82]:
facebook.groupby(['Category']).count()

,Page total likes,Type,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Category,,,,,,,,,,,,,,,,,,
1,215,215,215,215,215,215,215,215,215,215,215,215,215,215,215,214,211,215
2,130,130,130,130,130,129,130,130,130,130,130,130,130,130,130,130,130,130
3,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155,155

In [83]:
facebook.groupby(['Type']).count()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
Photo,426,426,426,426,426,425,426,426,426,426,426,426,426,426,426,425,422,426
Status,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45
Video,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7

# 2. Data Preprocessing

In [84]:
print(facebook[:10])

   Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441   Photo         2          12             4          3
1            139441  Status         2          12             3         10
2            139441   Photo         3          12             3          3
3            139441   Photo         2          12             2         10
4            139441   Photo         2          12             2          3
5            139441  Status         2          12             1          9
6            139441   Photo         3          12             1          3
7            139441   Photo         3          12             7          9
8            139441  Status         2          12             7          3
9            139441   Photo         3          12             6         10

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091
1   0.0                      10460                            19057
2   0.0                       2413                             4373
3   1.0                      50128                            87991
4   0.0                       7244                            13594
5   0.0                      10472                            20849
6   1.0                      11692                            19479
7   1.0                      13720                            24137
8   0.0                      11844                            22538
9   0.0                       4694                             8668

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109
1                    1457                     1361
2                     177                      113
3                    2211                      790
4                     671                      410
5                    1191                     1073
6                     481                      265
7                     537                      232
8                    1530                     1407
9                     280                      183

   Lifetime Post Consumptions  \
0                         159
1                        1674
2                         154
3                        1119
4                         580
5                        1389
6                         364
7                         305
8                        1692
9                         250

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078
1                                              11710
2                                               2812
3                                              61027
4                                               6228
5                                              16034
6                                              15432
7                                              19728
8                                              15220
9                                               4309

   Lifetime Post reach by people who like your Page  \
0                                              1640
1                                              6112
2                                              1503
3                                             32048
4                                              3200
5                                              7852
6                                              9328
7                                             11056
8                                              7912
9                                              2324

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119
1                                               1108
2                                                132
3                                               1386
4                                                396
5                                               1016
6                                                379
7                                                422
8                                               1250
9                                                199

   comment    like  share  Total Interactions
0        4    79.0   17.0                 100
1        5   130.0   29.0                 164
2        0    66.0   14.0                  80
3       58  1572.0  147.0                1777
4       19   325.0   49.0                 393
5        1   152.0   33.0                 186
6        3   249.0   27.0                 279
7        0   325.0   14.0                 339
8        0   161.0   31.0                 192
9        3   113.0   26.0                 142

In [85]:
#Check NaN per columns
facebook.isna().count()

Page total likes                                                       500
Type                                                                   500
Category                                                               500
Post Month                                                             500
Post Weekday                                                           500
Post Hour                                                              500
Paid                                                                   500
Lifetime Post Total Reach                                              500
Lifetime Post Total Impressions                                        500
Lifetime Engaged Users                                                 500
Lifetime Post Consumers                                                500
Lifetime Post Consumptions                                             500
Lifetime Post Impressions by people who have liked your Page           500
Lifetime Post reach by people who like your Page                       500
Lifetime People who have liked your Page and engaged with your post    500
comment                                                                500
like                                                                   500
share                                                                  500
Total Interactions                                                     500
dtype: int64

In [94]:
facebook.dropna(0,inplace=True)

In [95]:
lb = LabelBinarizer()
# Label Binarizer for Category (Action, Product and Inspiration)
lb_category=lb.fit_transform(facebook['Category'])
# Label Binarizer for Category (Link, Photo, Status and Video)
lb_type = lb.fit_transform(facebook['Type'])
lb_month = lb.fit_transform(facebook['Post Month'])
lb_weekday = lb.fit_transform(facebook['Post Weekday'])
lb_hour = lb.fit_transform(facebook['Post Hour'])

ValueError: y has 0 samples: Series([], Name: Category, dtype: float64)

In [93]:
# Label Binarizer for Category (Action, Product and Inspiration)
Action =[]
Product =[]
Inspiration=[]
Link=[]
Photo=[]
Status=[]
Video=[]
for i in range(len(facebook)):
    Action.append(lb_category[i][0])
    Product.append(lb_category[i][1])
    Inspiration.append(lb_category[i][2])
    Link.append(lb_type[i][0])
    Photo.append(lb_type[i][1])
    Status.append(lb_type[i][2])
    Video.append(lb_type[i][3])
    
facebook['Action']=Action
facebook['Product']=Product
facebook['Inspiration']=Inspiration
facebook['Link']=Link
facebook['Photo']=Photo
facebook['Status']=Status
facebook['Video']=Video
bin_var = [lb_month,lb_weekday,lb_hour]
for i in bin_var:
    i=pd.DataFrame(i)
    facebook=pd.concat([facebook,i])
facebook.columns

IndexError: index 500 is out of bounds for axis 0 with size 500

In [68]:
facebook.describe()

,0,1,2,3,4,5,6,7,8,9,...,Post Hour,Post Month,Post Weekday,Product,Status,Total Interactions,Video,comment,like,share
count,5000.000000,5000.000000,5000.000000,4000.000000,3000.000000,3000.000000,3000.000000,2000.000000,2000.000000,2000.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,499.000000,496.000000
mean,0.133600,0.274800,0.162000,0.082000,0.078000,0.097333,0.098000,0.046000,0.066000,0.138000,...,7.840000,7.038000,4.150000,0.260000,0.090000,212.120000,0.014000,7.48200,177.945892,27.266129
std,0.340256,0.446458,0.368488,0.274399,0.268216,0.296461,0.297364,0.209537,0.248344,0.344986,...,4.368589,3.307936,2.030701,0.439074,0.286468,380.233118,0.117608,21.18091,323.398742,42.613292
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,4.000000,2.000000,0.000000,0.000000,71.000000,0.000000,1.00000,56.500000,10.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.000000,7.000000,4.000000,0.000000,0.000000,123.500000,0.000000,3.00000,101.000000,19.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,11.000000,10.000000,6.000000,1.000000,0.000000,228.500000,0.000000,7.00000,187.500000,32.250000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,23.000000,12.000000,7.000000,1.000000,1.000000,6334.000000,1.000000,372.00000,5172.000000,790.000000

In [89]:
data_analysis= facebook.drop(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'], axis='columns')
data_analysis.columns

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,     10,     11,     12,     13,     14,     15,     16,     17,
           18,     19,     20,     21, 'Paid'],
      dtype='object')

In [70]:
X_train, X_test, y_train, y_test = train_test_split(data_analysis, facebook['Total Interactions'], test_size=0.2,random_state=0)
print(X_train.shape)
print(X_test.shape)

(4400, 30)
(1100, 30)

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn import tree # To get Decision Tree 
from sklearn import metrics # To generate evaluation metrices
from sklearn.model_selection import cross_val_predict # To generate evaluation metrices
from sklearn.model_selection import cross_val_score # To generate evaluation metrices


from sklearn.tree import export_graphviz # exporting the tree structure as dot file
from IPython.display import Image, SVG  # Show the image within colab notebook
import matplotlib.pyplot as plt # Plotting

In [2]:
SGD=SGDRegressor(loss='squared_loss', penalty='l1', alpha=0.0001,
                     l1_ratio=0.15, fit_intercept=True, max_iter=1000,
                     tol=0.001, shuffle=True, verbose=0, epsilon=0.1,
                     random_state=None, learning_rate='invscaling',
                     eta0=0.01, power_t=0.25, early_stopping=False,
                     validation_fraction=0.1, n_iter_no_change=5,
                     warm_start=False, average=False)
# #perform 10 fold cross validation and plot the CM
# CV_predicted = cross_val_predict(SGD, X_train, y_train, cv=10) #CV predicted values (training data)
# CV_score = cross_val_score(SGD, X_train, y_train, cv=10) #CV model score (training data)

# print("Cross validation Score on train data: ",CV_score.mean())
# print("\n")